// <auto-generated />
using System;
using BatterySwap.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BatterySwap.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BatterySwap.Domain.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.ActiveSwappingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CabinetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ActiveSwappingSessions", (string)null);
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.Battery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HealthState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("HolderId")
                        .HasColumnType("bigint");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Soc")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Voltage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Batteries", (string)null);
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.BatteryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BatteryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Soc")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<double>("Voltage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BatteryId", "RecordedAt");

                    b.ToTable("BatteryLogs", (string)null);
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.Cabinet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CabinetModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("StationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Cabinets", (string)null);
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.Slot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CabinetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CurrentBatteryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsHardwareLocked")
                        .HasColumnType("bit");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentBatteryId");

                    b.HasIndex("CabinetId", "SlotNumber")
                        .IsUnique();

                    b.ToTable("Slots", (string)null);
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.Station", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Stations", (string)null);
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.SwappingTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BatteryInId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BatteryOutId")
                        .HasColumnType("bigint");

                    b.Property<long>("CabinetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DispensedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SlotInId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SlotOutId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BatteryInId");

                    b.HasIndex("BatteryOutId");

                    b.HasIndex("CabinetId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SlotInId");

                    b.HasIndex("SlotOutId");

                    b.HasIndex("UserId");

                    b.ToTable("SwappingTransactions", (string)null);
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BalanceTrips")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.ActiveSwappingSession", b =>
                {
                    b.HasOne("BatterySwap.Domain.Entities.Cabinet", "Cabinet")
                        .WithMany("Sessions")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatterySwap.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.BatteryLog", b =>
                {
                    b.HasOne("BatterySwap.Domain.Entities.Battery", "Battery")
                        .WithMany("Logs")
                        .HasForeignKey("BatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battery");
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.Cabinet", b =>
                {
                    b.HasOne("BatterySwap.Domain.Entities.Station", "Station")
                        .WithMany("Cabinets")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.Slot", b =>
                {
                    b.HasOne("BatterySwap.Domain.Entities.Cabinet", "Cabinet")
                        .WithMany("Slots")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatterySwap.Domain.Entities.Battery", "CurrentBattery")
                        .WithMany()
                        .HasForeignKey("CurrentBatteryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cabinet");

                    b.Navigation("CurrentBattery");
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.SwappingTransaction", b =>
                {
                    b.HasOne("BatterySwap.Domain.Entities.Battery", "BatteryIn")
                        .WithMany()
                        .HasForeignKey("BatteryInId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BatterySwap.Domain.Entities.Battery", "BatteryOut")
                        .WithMany()
                        .HasForeignKey("BatteryOutId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BatterySwap.Domain.Entities.Cabinet", "Cabinet")
                        .WithMany("Transactions")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatterySwap.Domain.Entities.Slot", "SlotIn")
                        .WithMany()
                        .HasForeignKey("SlotInId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BatterySwap.Domain.Entities.Slot", "SlotOut")
                        .WithMany()
                        .HasForeignKey("SlotOutId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BatterySwap.Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BatteryIn");

                    b.Navigation("BatteryOut");

                    b.Navigation("Cabinet");

                    b.Navigation("SlotIn");

                    b.Navigation("SlotOut");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.Battery", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.Cabinet", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Slots");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.Station", b =>
                {
                    b.Navigation("Cabinets");
                });

            modelBuilder.Entity("BatterySwap.Domain.Entities.User", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
